/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ServicoBancoFuncionario;
import DAO.ServicoBancoPagMensal;
import classes.Calculo;
import classes.Funcionarios;
import classes.PagMensal;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author felipe.souza7
 */
public class Tela_lancamento extends javax.swing.JFrame {

    /**
     * Creates new form Tela_lancamento
     */
    public Tela_lancamento() {
        setLocationRelativeTo( null );
        initComponents();
    }
    
     Funcionarios fun;
     PagMensal pag;
     SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
      ServicoBancoFuncionario srvFuc = new ServicoBancoFuncionario();
      ServicoBancoPagMensal srv = new ServicoBancoPagMensal();
      Calculo calc = new Calculo();
      
      
      private void limparTela(){
        cbFuncionario.setSelectedIndex(-1);
        edPeriodo.setText("");
        edHorasTrabalhadas.setText("");
        edValorHora.setText("");
        edHorasTrabalhadas.requestFocus();
        btLimpar.setEnabled(true);
      }
    /**
     *
     * @throws SQLException
     */
    public void carregarComboBoxFuncionarios() throws SQLException{
        try {
            if (cbFuncionario.getItemCount() > 0){
               cbFuncionario.removeAllItems();
            }
        
          ArrayList<Funcionarios> lista = srvFuc.getFuncionarioByLista();
          
          for (Funcionarios u:lista){
            cbFuncionario.addItem(u);
          }      
        
          this.limparTela();
          
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
          };          
        
    }
    
    private void atualizarListaFuncionario(){
        try {
            if (cbFuncionario.getItemCount() >= 0){
               cbFuncionario.removeAllItems();
            }
        
          ArrayList<Funcionarios> lista = srvFuc.getFuncionarioByLista();
          
          for (Funcionarios u:lista){
            cbFuncionario.addItem(u);
          }      
        
          this.limparTela();
          
        } catch (SQLException ex) {
             Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
          }        
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbFuncionario = new javax.swing.JComboBox<>();
        edValorHora = new javax.swing.JTextField();
        edPeriodo = new javax.swing.JTextField();
        edHorasTrabalhadas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new Funcionarios[] {fun}));
        cbFuncionario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFuncionarioItemStateChanged(evt);
            }
        });
        getContentPane().add(cbFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 11, 262, -1));
        getContentPane().add(edValorHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 71, 144, -1));
        getContentPane().add(edPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 109, 144, -1));
        getContentPane().add(edHorasTrabalhadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 147, 46, -1));

        jLabel1.setText("Funcionario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 17, -1, -1));

        jLabel2.setText("Valor Hora:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 74, -1, -1));

        jLabel3.setText("Periodo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        jLabel4.setText("Horas Trabalhadas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        jButton1.setText("Voltar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, -1, -1));

        jButton2.setText("Lançar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 194, -1, -1));

        btLimpar.setText("Limpar");
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 194, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        int func = 0;
        double sal = 0;
        
        if (edHorasTrabalhadas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o nome do funcionario!");
            edHorasTrabalhadas.requestFocus();
            return;
        }
        
        if (edPeriodo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o cpf!");
            edPeriodo.requestFocus();
            return;
        }

        if (edValorHora.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o RG!");
            edValorHora.requestFocus();
            return;
        }
        
       
        
        
       try {
        if (cbFuncionario.getSelectedIndex() >= 0){ //alterar
            Funcionarios funcionario = (Funcionarios) cbFuncionario.getSelectedItem();
            edValorHora.setText(String.valueOf(funcionario.getValorHora()));
            PagMensal pagMensal = new PagMensal();
            
            pagMensal.setId_funcioanrio(funcionario.getId());
            pagMensal.setPeriodo(formato.parse(edPeriodo.getText()));
            pagMensal.setSalario(calc.calcularPagamento(Double.parseDouble(edValorHora.getText()), Double.parseDouble(edHorasTrabalhadas.getText())));
            
            func = pagMensal.getId_funcioanrio();
            sal = pagMensal.getSalario();
            
            srv.update(pagMensal);
           
        }
        else { //gravar
               PagMensal pagamento = new PagMensal(Integer.parseInt(edHorasTrabalhadas.getText()), func, sal, formato.parse(edPeriodo.getText()));
               srv.insert(pagamento);
               limparTela();
               
             }
        limparTela();
        this.atualizarListaFuncionario();
          
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            limparTela();
        } catch (ParseException ex) {
            Logger.getLogger(Tela_lancamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void cbFuncionarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFuncionarioItemStateChanged
         if (cbFuncionario.getItemCount() < 0){
            return;
        }
        
        if (cbFuncionario.getSelectedIndex() < 0){
            return;
        } 
        
        Funcionarios funcionario = (Funcionarios) cbFuncionario.getSelectedItem();
        edValorHora.setText(Double.toString(funcionario.getValorHora()));
        
        
    }//GEN-LAST:event_cbFuncionarioItemStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            atualizarListaFuncionario();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_lancamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JComboBox<Funcionarios> cbFuncionario;
    private javax.swing.JTextField edHorasTrabalhadas;
    private javax.swing.JTextField edPeriodo;
    private javax.swing.JTextField edValorHora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
