/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ServicoBancoFuncionario;
import classes.Funcionarios;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author felipe.souza7
 */
public class Tela_Cadastro extends javax.swing.JFrame {

    
    public Tela_Cadastro() {
        setLocationRelativeTo( null );
        initComponents();
    }
    
    ServicoBancoFuncionario srvFuc = new ServicoBancoFuncionario();
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
     Funcionarios fun;
    
    
    private void limparTela(){
        cbFuncionario.setSelectedIndex(-1);
        edNome.setText("");
        edCpf.setText("");
        edRg.setText("");
         edStatus.setText("");
          edDataNascimento.setText("");
           edGenero.setText("");
        edValorHora.setText("");
        edNome.requestFocus();
        btLimpar.setEnabled(true);
        
        
    }
    
    public void carregarComboBoxFuncionarios() throws SQLException{
        try {
            if (cbFuncionario.getItemCount() > 0){
               cbFuncionario.removeAllItems();
            }
        
          ArrayList<Funcionarios> lista = srvFuc.getFuncionarioByLista();
          
          for (Funcionarios u:lista){
            cbFuncionario.addItem(u);
          }      
        
          this.limparTela();
          
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
          };          
        
    }
    
    private void atualizarListaFuncionario(){
        try {
            if (cbFuncionario.getItemCount() >= 0){
               cbFuncionario.removeAllItems();
            }
        
          ArrayList<Funcionarios> lista = srvFuc.getFuncionarioByLista();
          
          for (Funcionarios u:lista){
            cbFuncionario.addItem(u);
          }      
        
          this.limparTela();
          
        } catch (SQLException ex) {
             Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
          }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbFuncionario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        edNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edCpf = new javax.swing.JTextField();
        edRg = new javax.swing.JTextField();
        edValorHora = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edStatus = new javax.swing.JTextField();
        edDataNascimento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edGenero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new Funcionarios[] {fun}));
        cbFuncionario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFuncionarioItemStateChanged(evt);
            }
        });
        getContentPane().add(cbFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 23, 393, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Funcionario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, -1));
        getContentPane().add(edNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 61, 393, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 64, -1, -1));
        getContentPane().add(edCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 187, -1));
        getContentPane().add(edRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 221, 187, -1));
        getContentPane().add(edValorHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 252, 187, -1));

        jButton1.setText("Voltar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        btSalvar.setText("Salvar");
        btSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 290, -1, -1));

        jButton3.setText("Excluir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 290, -1, -1));

        btLimpar.setText("Limpar");
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLimparMouseClicked(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RG:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 224, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Hora:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 255, -1, -1));
        getContentPane().add(edStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 159, 159, -1));
        getContentPane().add(edDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 128, 159, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de nascimento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 131, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));
        getContentPane().add(edGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 97, 159, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Genêro:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 100, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mobilization-For-Adaptive-Websites.gif"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 640, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        atualizarListaFuncionario();
    }//GEN-LAST:event_formWindowActivated

    private void btSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalvarMouseClicked
        if (edNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o nome do funcionario!");
            edNome.requestFocus();
            return;
        }
        
        if (edCpf.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o cpf!");
            edCpf.requestFocus();
            return;
        }

        if (edRg.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o RG!");
            edRg.requestFocus();
            return;
        }
        
        if (edValorHora.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o valor da hora!");
            edValorHora.requestFocus();
            return;
        }
        
        if (edStatus.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o status do funcionario!");
            edStatus.requestFocus();
            return;
        }
        
        if (edDataNascimento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe a data de nascimento do funcionario!");
            edDataNascimento.requestFocus();
            return;
        }
        
        if (edGenero.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o genero do funcionario!");
            edGenero.requestFocus();
            return;
        }
        
        
       try {
        if (cbFuncionario.getSelectedIndex() >= 0){ //alterar
            Funcionarios funcionario = (Funcionarios) cbFuncionario.getSelectedItem();
            
            funcionario.setNome(edNome.getText());
            funcionario.setGenero(edGenero.getText());
            funcionario.setStatus(edStatus.getText());
            funcionario.setData_nascimento((Date)formato.parse(edDataNascimento.getText()));
            funcionario.setCpf(edCpf.getText());
            funcionario.setRg(edRg.getText());
            funcionario.setValorHora(Double.parseDouble(edValorHora.getText()));
            
            srvFuc.update(funcionario);
           
        }
        else { //gravar
               Funcionarios funcionario = new Funcionarios(edNome.getText(),edGenero.getText(), (Date)formato.parse(edDataNascimento.getText()), edStatus.getText(), edRg.getText(), edCpf.getText(), Double.parseDouble(edValorHora.getText()) );
               srvFuc.insert(funcionario);
               limparTela();
               
             }
        limparTela();
        this.atualizarListaFuncionario();
          
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            limparTela();
        } catch (ParseException ex) {
            Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSalvarMouseClicked

    private void cbFuncionarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFuncionarioItemStateChanged
         if (cbFuncionario.getItemCount() < 0){
            return;
        }
        
        if (cbFuncionario.getSelectedIndex() < 0){
            return;
        } 
        
        Funcionarios funcionario = (Funcionarios) cbFuncionario.getSelectedItem();
        edNome.setText(funcionario.getNome());
        edStatus.setText(funcionario.getStatus());
        edDataNascimento.setText(formato.format(funcionario.getData_nascimento()));
        edGenero.setText(funcionario.getGenero());
        edCpf.setText(funcionario.getCpf());
        edRg.setText(funcionario.getRg());
        edValorHora.setText(String.valueOf(funcionario.getValorHora()));
        
        btLimpar.setEnabled(true);
    }//GEN-LAST:event_cbFuncionarioItemStateChanged

    private void btLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseClicked
        limparTela();
    }//GEN-LAST:event_btLimparMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (cbFuncionario.getSelectedIndex() < 0)
            return;
        
        //resp--> 0 = yes 1 = no 2 = cancel
        int resp = JOptionPane.showConfirmDialog(null, "Excluir registro?");
        if (resp == 0){
            try {
                srvFuc.delete((Funcionarios) cbFuncionario.getSelectedItem());
                
                this.atualizarListaFuncionario();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<Funcionarios> cbFuncionario;
    private javax.swing.JTextField edCpf;
    private javax.swing.JTextField edDataNascimento;
    private javax.swing.JTextField edGenero;
    private javax.swing.JTextField edNome;
    private javax.swing.JTextField edRg;
    private javax.swing.JTextField edStatus;
    private javax.swing.JTextField edValorHora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
